name = "vhelp-api"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[alias]
"node:hono" = "hono"
"node:hono/cors" = "hono/cors"

[[kv_namespaces]]
binding = "STORAGE"
id = "d2753065581948aaab0aa4357a7ebc36"

[[d1_databases]]
binding = "DB"
database_name = "vhelp-db"
database_id = "4ec9fbb8-0881-4c1f-839e-48fb5c918ae3"

[vars]
FRONTEND_URL = "https://vhelp.vercel.app"
NODE_ENV = "production"

# Секреты добавляйте через: wrangler secret put KEY
# MONGODB_URI
# JWT_SECRET
# VK_CLIENT_SECRET
