name = "vhelp" 
compatibility_date = "2024-01-01" 
pages_build_output_dir = "dist"

# D1 database binding 
[[d1_databases]] 
binding = "DB" 
database_name = "vhelp-db" 
database_id = "4ec9fbb8-0881-4c1f-839e-48fb5c918ae3" 

# Environment variables 
[vars] 
JWT_SECRET = "your_jwt_secret_key_here_minimum_32_characters" 
NODE_ENV = "production"
