name = "vhelp-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "vhelp-db"
database_id = "4ec9fbb8-0881-4c1f-839e-48fb5c918ae3"

[vars]
JWT_SECRET = "your-secret-key-min-32-chars-long"
